# Generated by Django 6.0.6 on 2026-06-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cedula_remove_cliente_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='fecha_fin',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_inmueble',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='precio_mensual',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='tipo',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio',
            field=models.IntegerField(default='Sin nombre'),
            preserve_default=False,
        ),
    ]
