# Generated by Django 6.0.6 on 2026-06-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_fecha_fin_arriendo_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(default=None, upload_to='inmuebles/'),
            preserve_default=False,
        ),
    ]
