# Generated by Django 6.0.6 on 2026-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_inmueble_direccion_alter_inmueble_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='nombre',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='banos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ciudad',
            field=models.CharField(default='Ciudad', max_length=50),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(default='Dirección', max_length=100),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='habitaciones',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(default='Apartamento', max_length=50),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, max_length=15),
        ),
    ]
